.PHONY: clean All

All:
	@echo "----------Building project:[ q1_geometria - Release ]----------"
	@cd "q1_geometria" && "$(MAKE)" -f  "q1_geometria.mk"
clean:
	@echo "----------Cleaning project:[ q1_geometria - Release ]----------"
	@cd "q1_geometria" && "$(MAKE)" -f  "q1_geometria.mk" clean
